services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./apps/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=eric
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=first_db