services:
  mysql:
    image: "mysql:lts"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./my_config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/logs
    environment:
      MYSQL_USER: eric
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: siang_gin
