version: '3.5'
services:
  db:
    image: "mariadb:latest"
    ports:
      - "3307:3307"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"